### ISSUE TITLE
Add modal asking if user really wants to delete the current class in classroom index

### ISSUE THREAD

**Issue by Marcos-Costa** [euodeionomedeusuario/classroom#4]
![image](https://user-images.githubusercontent.com/19848508/40194433-cf01130c-59e0-11e8-9cd5-af1e4bfde9f4.png)

**Comment by euodeionomedeusuario** [comment]
@Marcos-Costa, it is done!  

![screenshot-2018-5-17 classroom 1](https://user-images.githubusercontent.com/20930257/40211428-1ac05ef2-5a21-11e8-83ba-f93519e47903.png)

**Comment by Marcos-Costa** [comment]
Much better! Thx. :smile:
